version: '3'

services:
  go_super_admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatwoot-go-super-admin:latest
    network_mode: host
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=chatwoot
      - POSTGRES_DATABASE=chatwoot
      - REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-super-admin-dev-secret}
      - SUPER_ADMIN_PORT=4000
    env_file:
      - ../.env
    restart: unless-stopped
